### ISSUE TITLE
References don't render nicely

### ISSUE THREAD

**Issue by jhand2** [TrustedComputingGroup/markdown#49]
This markdown:

```
# References

[1] Trusted Computing Group, "DICE Protection Environment," 2023. [Online].
    Available: https://trustedcomputinggroup.org.

[2] Trusted Computing Group, "DICE Certificate Profiles," 2020. [Online].
    Available: https://trustedcomputinggroup.org.

[3] Internet Engineering Task Force, "Cryptographic Message Syntax (CMS)," 2009. [Online].
    Avilable: https://www.ietf.org/rfc/rfc5652.txt

[4] Internet Engineering Task Force, "PKCS #10: Certification Request Syntax Specification Version 1.7," 2000. [Online].
    Avilable: https://www.ietf.org/rfc/rfc2986.txt
```

Renders like this:

![Screenshot 2023-03-23 at 5 21 04 PM](https://user-images.githubusercontent.com/11011105/227392896-a60ef71f-d41f-4032-ae7b-f28531e5791f.png)

A couple issues:

* Spacing is a bit tight. I'm not sure if there's a good way to artificially add more spacing
* The margin wrapping doesn't seem to be working correctly. See how the link doesn't wrap in reference 3, but the wrapping does work in reference 4

**Comment by jhand2** [comment]
I think this has to do with how wrapping paths/URLs works. If I make them links, then the wrapping works (sort of).

This markdown:

```
# References

1. Trusted Computing Group, "DICE Protection Environment," 2023. [Online].
   Available: <https://trustedcomputinggroup.org>.

2. Trusted Computing Group, "DICE Certificate Profiles," 2020. [Online].
   Available: <https://trustedcomputinggroup.org>.

3. Internet Engineering Task Force, "Cryptographic Message Syntax (CMS)," 2009.
   [Online]. Avilable: <https://www.ietf.org/rfc/rfc5652.txt>.

4. Internet Engineering Task Force,
   "PKCS #10: Certification Request Syntax Specification Version 1.7," 2000.
   [Online]. Avilable: <https://www.ietf.org/rfc/rfc2986.txt>.
```

Renders like:

<img width="825" alt="Screenshot 2023-03-27 at 4 40 12 PM" src="https://user-images.githubusercontent.com/11011105/228090985-f55b2673-5a5c-4050-8d16-fbd76583c4fb.png">

This is more reasonable, although it would be nice if the whole link dropped to the next line, instead of splitting in the middle of the link. I think this behavior has something to do with this line in the latex template: https://github.com/TrustedComputingGroup/pandoc/blob/038017d3e67f3fd27bfaa56ee412eb739d1854e8/template/eisvogel.latex#L251

**Comment by chrisfenner** [comment]
Fixed with https://github.com/TrustedComputingGroup/pandoc/releases/tag/v0.4.1
